// Generated by gencpp from file template_pkg/Person_srv.msg
// DO NOT EDIT!


#ifndef TEMPLATE_PKG_MESSAGE_PERSON_SRV_H
#define TEMPLATE_PKG_MESSAGE_PERSON_SRV_H

#include <ros/service_traits.h>


#include <template_pkg/Person_srvRequest.h>
#include <template_pkg/Person_srvResponse.h>


namespace template_pkg
{

struct Person_srv
{

typedef Person_srvRequest Request;
typedef Person_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person_srv
} // namespace template_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::template_pkg::Person_srv > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::template_pkg::Person_srv&) { return value(); }
};

template<>
struct DataType< ::template_pkg::Person_srv > {
  static const char* value()
  {
    return "template_pkg/Person_srv";
  }

  static const char* value(const ::template_pkg::Person_srv&) { return value(); }
};


// service_traits::MD5Sum< ::template_pkg::Person_srvRequest> should match
// service_traits::MD5Sum< ::template_pkg::Person_srv >
template<>
struct MD5Sum< ::template_pkg::Person_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::template_pkg::Person_srv >::value();
  }
  static const char* value(const ::template_pkg::Person_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::template_pkg::Person_srvRequest> should match
// service_traits::DataType< ::template_pkg::Person_srv >
template<>
struct DataType< ::template_pkg::Person_srvRequest>
{
  static const char* value()
  {
    return DataType< ::template_pkg::Person_srv >::value();
  }
  static const char* value(const ::template_pkg::Person_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::template_pkg::Person_srvResponse> should match
// service_traits::MD5Sum< ::template_pkg::Person_srv >
template<>
struct MD5Sum< ::template_pkg::Person_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::template_pkg::Person_srv >::value();
  }
  static const char* value(const ::template_pkg::Person_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::template_pkg::Person_srvResponse> should match
// service_traits::DataType< ::template_pkg::Person_srv >
template<>
struct DataType< ::template_pkg::Person_srvResponse>
{
  static const char* value()
  {
    return DataType< ::template_pkg::Person_srv >::value();
  }
  static const char* value(const ::template_pkg::Person_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEMPLATE_PKG_MESSAGE_PERSON_SRV_H
