// Generated by gencpp from file template_pkg/Person_srvRequest.msg
// DO NOT EDIT!


#ifndef TEMPLATE_PKG_MESSAGE_PERSON_SRVREQUEST_H
#define TEMPLATE_PKG_MESSAGE_PERSON_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace template_pkg
{
template <class ContainerAllocator>
struct Person_srvRequest_
{
  typedef Person_srvRequest_<ContainerAllocator> Type;

  Person_srvRequest_()
    : name()
    , age(0)
    , sex(0)  {
    }
  Person_srvRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , sex(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint8_t _sex_type;
  _sex_type sex;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(male)
  #undef male
#endif
#if defined(_WIN32) && defined(female)
  #undef female
#endif

  enum {
    unknown = 0u,
    male = 1u,
    female = 2u,
  };


  typedef boost::shared_ptr< ::template_pkg::Person_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::template_pkg::Person_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Person_srvRequest_

typedef ::template_pkg::Person_srvRequest_<std::allocator<void> > Person_srvRequest;

typedef boost::shared_ptr< ::template_pkg::Person_srvRequest > Person_srvRequestPtr;
typedef boost::shared_ptr< ::template_pkg::Person_srvRequest const> Person_srvRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::template_pkg::Person_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::template_pkg::Person_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::template_pkg::Person_srvRequest_<ContainerAllocator1> & lhs, const ::template_pkg::Person_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.sex == rhs.sex;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::template_pkg::Person_srvRequest_<ContainerAllocator1> & lhs, const ::template_pkg::Person_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace template_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::template_pkg::Person_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::template_pkg::Person_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::template_pkg::Person_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3f7ec37d11629ec3010e27635cf22a9";
  }

  static const char* value(const ::template_pkg::Person_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3f7ec37d11629ecULL;
  static const uint64_t static_value2 = 0x3010e27635cf22a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "template_pkg/Person_srvRequest";
  }

  static const char* value(const ::template_pkg::Person_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint8  age\n"
"uint8  sex\n"
"\n"
"uint8 unknown = 0\n"
"uint8 male    = 1\n"
"uint8 female  = 2\n"
"\n"
;
  }

  static const char* value(const ::template_pkg::Person_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.sex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::template_pkg::Person_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::template_pkg::Person_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "sex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMPLATE_PKG_MESSAGE_PERSON_SRVREQUEST_H
